### ISSUE TITLE
assets not being loaded when slim is instantiated in subdirectories.

### ISSUE THREAD

**Issue by Langmans** [yusukezzz/slim-debugbar#3]
https://github.com/yusukezzz/slim-debugbar/blob/master/src/Slim/Middleware/DebugBar.php#L144

I think you'd need $app->request()->getRootUri() :)

**Comment by borgogelli** [comment]
Same problem for me. 
The code
<pre><link rel="stylesheet" type="text/css" href="/_debugbar/resources/dump.css"></pre>
is not a valid css link

**Comment by borgogelli** [comment]
Same problem for me. 
The code
 
   <link rel="stylesheet" type="text/css" href="/_debugbar/resources/dump.css">
 
is not a valid css link

**Comment by yusukezzz** [comment]
#4 merged and released v1.1.1
Thanks.
