### ISSUE TITLE
Only for technical curiosity. It's not an issue

### ISSUE THREAD

**Issue by borgogelli** [yusukezzz/slim-debugbar#5]
I use your code with the Twig view.
It works fine, ....too fine for me

Indeed when I write

<pre>
$this->app->render();
$this->app->log->debug('Writing a log message after page rendering.');
</pre>

I could read the log message in the debug bar, while if I don't use your code, but the raw DebugBar code, the message is never showed.

Why ?

Thank you in advance

**Comment by yusukezzz** [comment]
Thank you for your interest.
I'll try to investigate it.

**Comment by yusukezzz** [comment]
Sorry for late reply.
And my english is poor, sorry (Many helped by google translator).

I have understand your question as,

```
When I use slim-debugbar middleware,
Why to be seen the log message in my browser even though after the rendering is finished ?
```

Right?

It is recommended to understand the mechanism of Slim middleware.
Slim middleware is able to hook the before and after handle of the request.
Please read [this article](http://www.sitepoint.com/working-with-slim-middleware/) for more information.

Timeline of this pattern is below.

```
Start Request
...
Middleware Before
Initialize DebugBar instance
...
Execute your code
$this->app->render();
$this->app->log->debug('Writing a log message after page rendering.');
...
Middleware After
Collect debug data and modify html response to append DebugBar JS code
Yes, include log message after render() method
...
Finish request
Finalize response data and echo
```
