### ISSUE TITLE
Resource interpreted as Font but transferred with MIME type text/html

### ISSUE THREAD

**Issue by borgogelli** [yusukezzz/slim-debugbar#6]
Hi

FontsAwesome's fonts are not loaded, and so icons on toolbar are not rendered

Here the errors in the browser's console:

<pre>
Resource interpreted as Font but transferred with MIME type text/html: "http://.../_debugbar/fonts/fontawesome-webfont.woff2?v=4.3.0".page:1
Resource interpreted as Font but transferred with MIME type text/html: "http://.../_debugbar/fonts/fontawesome-webfont.woff?v=4.3.0".page:1 
Resource interpreted as Font but transferred with MIME type text/html: "http://.../_debugbar/fonts/fontawesome-webfont.ttf?v=4.3.0".
</pre>

The raw DebugBar and Slim are working fine together, no fonts problem.

Any advice ? 

Regards

Andrea

**Comment by borgogelli** [comment]
Solution: enable 
<pre>extension=php_fileinfo.dll</pre>
in php.ini

**Comment by borgogelli** [comment]
Solution:

I have enabled the following php extension in the php.ini config file

<pre>extension=php_fileinfo.dll</pre>

Then a new error is shown in the browser console;

<pre>
GET: .../fontawesome-webfont.woff2?v=4.3.0 
</pre>

That font is missing from the DebugBar package too (but there is no error with that package)
So I have downloaded the fonts-awesome zip archive from the web. 
Then I have extracted the missing font in the DebugBar's fonts path (inside the vendor folder).

And now everything is working fine !

Regards from Italy

Andrea

**Comment by yusukezzz** [comment]
Thank you for the solution.
I'll add this solution to README.
