### ISSUE TITLE
Resources not loaded

### ISSUE THREAD

**Issue by hernandes** [yusukezzz/slim-debugbar#7]
I am using the example of the project, and the run is not loading the resources, I noticed something related to the pass ".js" for example on the route to search files

![captura de tela 2015-04-06 as 09 55 32](https://cloud.githubusercontent.com/assets/415107/7004536/30851f84-dc43-11e4-8ab8-e788e21778d4.png)

**Comment by yusukezzz** [comment]
Are you using php builtin server?
Currently not working on that, sorry.
It seems slim virtual-path and physical-path has not been properly configured.

**Comment by hernandes** [comment]
Yes, Iam using builtin server :(

**Comment by yusukezzz** [comment]
OK, I'll add this issue to README.
Please use real httpd (apache, nginx etc...).

**Comment by yusukezzz** [comment]
Update README and release v1.1.1
Thanks.
