### ISSUE TITLE
Active debugbar eliminates jquery onload

### ISSUE THREAD

**Issue by solidevolution** [yusukezzz/slim-debugbar#9]
In our large slim application with propel & twig, we integrated the slim-debugbar to catch informations about session data and database.

We did it simple with

 $debugbar = new \Slim\Middleware\DebugBar();
 $app->add($debugbar);

The toolbar works but all .js crashes (Plugins like validate & datatables aren't able to find jquery)

I think it must be an issue with the document-ready handler. Anyone else integrated slim-debugbar with jquery?

**Comment by yusukezzz** [comment]
Sorry for late reply. 
It seems to need jQuery.noConflict();
I think it shoud be the default behaviour in DebugBar so I'll fix this issue.

**Comment by yusukezzz** [comment]
@solidevolution I'm pushed workaround for this issue https://github.com/yusukezzz/slim-debugbar/commit/ffaaa4c5f3f284af00ee46807b790484979756a2

Please check dev-master.
I'll release this to v1.1.2 if no problem.
